version: "3.9"

services:
  flask-api:
    container_name: local-flask-api
    depends_on:
      dynamo:
       condition: service_healthy
    image: dockerelvis/flask-demo:latest
    networks:
      - local-dynamodb
    env_file: variables.env
    ports:
      - "9002:9001"
    links:
      - dynamo
    volumes:
      - ~/.aws/:/root/.aws:ro

  dynamo:
    container_name: local-dynamodb
    image: amazon/dynamodb-local
    networks:
      - local-dynamodb
    ports:
      - "8000:8000"
    volumes:
      - dynamodata:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/shell/ || exit 0" ]
      interval: 1s
      timeout: 10s
      retries: 3

networks:
  local-dynamodb:
    name: local-dynamodb

volumes:
  dynamodata: {}
